runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Java SDK 17
      uses: actions/setup-java@v3.13.0
      with:
        java-version : '17'
        distribution : 'adopt'
    - name: Unit tests
      shell: bash
      run: bash ./gradlew test
    - name: Unit tests results
      if: success() || failure()
      uses: actions/upload-artifact@v3
      with:
        name: unit-tests-results   
        path: app/build/reports/tests/testDebugUnitTest/index.html
