#!/bin/sh
stagedFiles=$(git diff --staged --name-only)

echo "
===============
|  Running spotless check...
===============
"
./gradlew spotlessApply
EXIT_CODE=$?
if [ ${EXIT_CODE} -eq 0 ]; then
  echo "*********************************************"
  echo "           Spotless Check Succeed            "
  echo "*********************************************"
  for file in $stagedFiles; do
    if test -f "$file"; then
      git add $file
    fi
  done
else
  echo "*********************************************"
  echo "            Spotless Check Failed           "
  echo "Please fix the above issues before committing"
  echo "*********************************************"
#  exit ${EXIT_CODE}
fi

echo "
===============
|  Running lint check...
===============
"
./gradlew clean lint
EXIT_CODE=$?
if [ ${EXIT_CODE} -eq 0 ]; then
  echo "*********************************************"
  echo "           Lint Check Succeed            "
  echo "*********************************************"
  for file in $stagedFiles; do
    if test -f "$file"; then
      git add $file
    fi
  done
else
  echo "*********************************************"
  echo "            Lint Check Failed           "
  echo "Please fix the above issues before committing"
  echo "*********************************************"
  exit ${EXIT_CODE}
fi
