# When it will be triggered
on:
  push:
    branches: [ main ]
    
jobs:
  Unit_Test:
    runs-on: ubuntu-latest
    steps:
      - id: Unit_Test
      - uses: ./.github/actions/unit-test
  Unit_Test1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: Unit_Test1
        uses: actions/checkout@v1
      - uses: ./.github/actions/unit-test
  Unit_Test2:
    needs: [Unit_Test, Unit_Test1]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run : |
          echo jobs.Unit_Test.status
