# When it will be triggered
on:
  push:
    branches: [ main ]
    
jobs:
  Unit_Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: Unit_Test
        # uses: actions/checkout@v1
        run: echo "Unit_Test"
      # - uses: ./.github/actions/unit-test
  Unit_Test1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: Unit_Test1
        # uses: actions/checkout@v1
        run: echo "Unit_Test1"
      # - uses: ./.github/actions/unit-test
  Unit_Test2:
    needs: [Unit_Test, Unit_Test1]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run : |
          echo job.status
  slack:
    runs-on: ubuntu-latest
    needs: Unit_Test2
    steps:
      - uses: 8398a7/action-slack@v3
        with:
          mention: 'C070PCJAW77'
          fields: repo,commit,author,ref,workflow,job,took
          text: 'Success'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
