# When it will be triggered
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      brand:
        type: choice
        description: Select the brand
        options:
          - Nissan
          - Infinti
      region:
        type: choice
        description: Select the region
        options:
          - Eur
          - Uae
          - Asia
          - Ukr
          - Aus
      environment:
        type: choice
        description: Select the environment
        options:
          - Int
          - PreProd
          - Prod
      publishing_format:
        type: choice
        description: Select the Publishing Format
        options:
          - .aab
          - .apk
      artifact:
        description: Upload Build Artifact
        required: false
        type: boolean
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    # - name: Build Release
    #   run: |
    #     echo "buildVariant=${{ inputs.brand }}${{ inputs.region }}${{ inputs.environment }}" >> "$GITHUB_ENV"
    # - name: Echo Build Variant
    #   run: |
    #     echo ${{ env.buildVariant }}
    #     echo ${{ github.event_name }}

    - name: Decode Keystore
      run: |
          if [ ${{ github.event_name}} == 'push' ]; then
            echo "Push Request"
          elif [ ${{ github.event_name}} == 'pull_request' ]; then
            echo "Before Merged"
            if: github.event.pull_request.merged == true
            echo "After Merged"

  # lint:
  #   name: Run Lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v1
  #     - name: Setup Java SDK 17
  #       uses: actions/setup-java@v3.13.0
  #       with:
  #         java-version : '17'
  #         distribution : 'adopt'
  #     - name: Run Lint
  #       run: ./gradlew lint
  #     - name: Check and report lint results
  #       uses: hidakatsuya/action-report-android-lint@v1.1.3
  #       with:
  #         result-path: 'app/build/reports/lint-results-debug.xml'
