# When it will be triggered
on:
  push:
    branches: [ main ]
    
jobs:
  Unit_Test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/unit-test
  Unit_Test1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: hello
        uses: actions/checkout@v1
      - uses: ./.github/actions/unit-test
  Unit_Test2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run :
          echo jobs.hello.status
