# When it will be triggered
on:
  push:
    branches: [ main ]
    
jobs:
  Unit_Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: ./.github/actions/unit-test
  
